use_frameworks!

def addSendKin
  pod 'SendKin', :path => '../'
end

target 'SendKin-Sender' do
  addSendKin
end

target 'SendKin-Receiver' do
  addSendKin
end

target 'send-kin-module-ios_Tests' do
  addSendKin
end
